// This file will be auto-generated by Supabase CLI after schema creation
// For now, using a placeholder type structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      emergencies: {
        Row: {
          id: string;
          created_at: string;
          emergency_type: string;
          description: string | null;
          location_lat: number | null;
          location_lng: number | null;
          location_address: string | null;
          urgency: string;
          people_affected: number | null;
          specific_needs: Json | null;
          status: string;
          requester_contact: string | null;
          ai_extracted_data: Json | null;
          has_children: boolean;
          has_elderly: boolean;
          has_disabilities: boolean;
        };
        Insert: Omit<Database['public']['Tables']['emergencies']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['emergencies']['Insert']>;
      };
      volunteers: {
        Row: {
          id: string;
          user_id: string | null;
          created_at: string;
          name: string;
          email: string | null;
          phone: string | null;
          location_lat: number | null;
          location_lng: number | null;
          location_address: string | null;
          skills: Json | null;
          availability: string | null;
          max_distance_miles: number;
          emergency_preferences: Json | null;
          total_missions: number;
          rating: number;
          is_active: boolean;
        };
        Insert: Omit<Database['public']['Tables']['volunteers']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['volunteers']['Insert']>;
      };
      businesses: {
        Row: {
          id: string;
          user_id: string | null;
          created_at: string;
          business_name: string;
          contact_name: string | null;
          email: string | null;
          phone: string | null;
          location_lat: number | null;
          location_lng: number | null;
          location_address: string | null;
          resources: Json | null;
          resource_descriptions: string | null;
          availability_duration: string | null;
          auto_match: boolean;
        };
        Insert: Omit<Database['public']['Tables']['businesses']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['businesses']['Insert']>;
      };
      matches: {
        Row: {
          id: string;
          created_at: string;
          emergency_id: string;
          volunteer_id: string | null;
          business_id: string | null;
          match_score: number | null;
          match_reasoning: string | null;
          status: string;
          accepted_at: string | null;
          completed_at: string | null;
          feedback_rating: number | null;
          feedback_notes: string | null;
        };
        Insert: Omit<Database['public']['Tables']['matches']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['matches']['Insert']>;
      };
    };
  };
}
